config/routes.rb
Rails.application.routes.draw do
  get 'seller/index'

  get 'user/index'

  resources :sellers do
     resources :gigs
  end

  root 'user#index'

end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to :seller
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	has_many :gigs
	validates :name, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
	http_basic_authenticate_with name: "test", password: "admin", only: [:destroy]
	def create
    @seller = Seller.find(params[:seller_id])
    @gig = @seller.gigs.create(gig_params)
    redirect_to seller_path(@seller)
  end

  def destroy
    @seller= Seller.find(params[:seller_id])
    @gig = @seller.gigs.find(params[:id])
    @gig.destroy
    redirect_to seller_path(@seller)
  end

 
  private
    def gig_params
      params.require(:gig).permit(:title, :context)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  http_basic_authenticate_with name: "test", password: "admin", except: [:index, :show]
  def index
    @sellers = Seller.all
  end

  def new
    @seller = Seller.new(params[:id])
  end

  def create
  	@seller = Seller.new(seller_params)

    if @seller.save
    redirect_to @seller
    else
    render 'new'
    end
  end

  def show
  @seller = Seller.find(params[:id])
  end

  def edit
  @seller= Seller.find(params[:id])
  end

  def update
   @seller = Seller.find(params[:id])
 
    if @seller.update(seller_params)
    redirect_to @seller
    else
    render 'edit'
   end
  end

  def destroy
  @seller = Seller.find(params[:id])
  @seller.destroy
  redirect_to sellers_path
end

  private
  def seller_params
    params.require(:seller).permit(:name, :about)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gigs/_form.html.erb
<%= form_for([@seller, @seller.gigs.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :context %><br>
    <%= f.text_area :context %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/gigs/_gig.html.erb
<p>
  <strong>Gig:</strong>
  <%= gig.title %>
</p>
 
<p>
  <strong>Context:</strong>
  <%= gig.context %>	
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testtask</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sellers/_form.html.erb
<%= form_for @seller do |f| %>
  <% if @seller.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@seller.errors.count, "error") %> prohibited
      this seller profile from being saved:</h2>
    <ul>
    <% @seller.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sellers/edit.html.erb
<h1>Edit seller profile</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<h1>Listing seller profiles</h1>
<%= link_to 'New seller profile', new_seller_path %>
<table>
  <tr>
    <th>Name</th>
    <th>About</th>
    <th colspan="3"></th>
  </tr>
 
<% @sellers.each do |seller| %>
  <tr>
    <td><%= seller.name %></td>
    <td><%= seller.about %></td>
    <td><%= link_to 'Show', seller_path(seller) %></td>
    <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
    <%#= link_to 'Destroy', seller_path(seller),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
  </tr>
<% end %>
</table>

app/views/sellers/new.html.erb
<h1>New seller profile</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>
 
<p>
  <strong>About:</strong>
  <%= @seller.about %>
</p>

<h2>Gigs</h2>
<%= render @seller.gigs %>
 
<h2>Add a Gig:</h2>
<%= render "gigs/form" %>

<%= link_to 'Back', sellers_path %>
| <%= link_to 'Edit', edit_seller_path(@seller) %>

app/views/user/index.html.erb
<h1>WELCOME</h1>
<%= link_to 'seller', controller: 'sellers' %>